#!/bin/bash

#Messages and actions

echo "get last changes"
git pull

echo "upload changes to git"

echo "git add . --all"
git add . --all

echo "git commit -am $1"
git commit -am "$1"

echo "git push"
git push

echo "myGit ends"

#End
